import type { ProfileSummary } from "./learning-store";

function pdfText(value: string) {
  return value
    .replace(/[^\x20-\x7e]/g, "?")
    .replace(/\\/g, "\\\\")
    .replace(/\(/g, "\\(")
    .replace(/\)/g, "\\)");
}

function escapePdfBytes(value: string) {
  return Buffer.from(value, "latin1");
}

export function buildProfileSummaryPdf(summary: ProfileSummary) {
  const lines = [
    "TAWJEEH PROFILE SUMMARY",
    `Name: ${summary.profile.name}`,
    `Grade: ${summary.profile.grade}`,
    `Daily points: ${summary.daily_points.points}/${summary.daily_points.target}`,
    `Emergency error rate threshold: ${Math.round(summary.policy.emergency_error_rate * 100)}%`,
    `Daily points target: ${summary.policy.daily_points_target}`,
    "",
    "Concept metrics:",
    ...summary.metrics.slice(0, 30).map(
      (metric) =>
        `- ${metric.lesson_title} / ${metric.concept_title}: ${Math.round(metric.error_rate * 100)}% errors (${metric.errors_count}/${metric.attempts})`,
    ),
    "",
    "This file was generated by Tawjeeh and stored in Replit App Storage.",
  ];
  const stream = [
    "BT",
    "/F1 11 Tf",
    "50 760 Td",
    ...lines.flatMap((line, index) => [
      index === 0 ? `(${pdfText(line)}) Tj` : "0 -16 Td",
      index === 0 ? "" : `(${pdfText(line)}) Tj`,
    ]).filter(Boolean),
    "ET",
  ].join("\n");
  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    `<< /Length ${Buffer.byteLength(stream, "latin1")} >>\nstream\n${stream}\nendstream`,
  ];
  const chunks = ["%PDF-1.4\n"];
  const offsets = [0];
  for (let index = 0; index < objects.length; index += 1) {
    offsets.push(Buffer.byteLength(chunks.join(""), "latin1"));
    chunks.push(`${index + 1} 0 obj\n${objects[index]}\nendobj\n`);
  }
  const xrefOffset = Buffer.byteLength(chunks.join(""), "latin1");
  chunks.push(`xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`);
  for (const offset of offsets.slice(1)) chunks.push(`${String(offset).padStart(10, "0")} 00000 n \n`);
  chunks.push(`trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`);
  return escapePdfBytes(chunks.join(""));
}