// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/tawjeeh-auth/Current.tsx": () => import("../components/mockups/tawjeeh-auth/Current.tsx"),
  "./components/mockups/tawjeeh-reimagined/ExamBoard.tsx": () => import("../components/mockups/tawjeeh-reimagined/ExamBoard.tsx"),
  "./components/mockups/tawjeeh-reimagined/ExamBoardV2.tsx": () => import("../components/mockups/tawjeeh-reimagined/ExamBoardV2.tsx"),
  "./components/mockups/tawjeeh-reimagined/SignIn.tsx": () => import("../components/mockups/tawjeeh-reimagined/SignIn.tsx"),
  "./components/mockups/tawjeeh-reimagined/SignInV2.tsx": () => import("../components/mockups/tawjeeh-reimagined/SignInV2.tsx")
};
